# Admin companies

winter-solstice-description = All three branches of the Trans-Solar Marines Federation fall under the direction of the Federation's unified high command, known as Winter Solstice.


# Core companies

drake-industries-description = Efficiency, profits, reliability. Drake Industries is a former major trade company that turned itself into the largest industry giant within the sector. From sleek civilian ship designs to material refining, it keeps itself afloat mainly by fueling the surrounding conflicts. Officially, it discourages any kind of hostilities performed by the members of the company. It promises easy profits to all capable pilots, engineers & private securities willing to enroll under their banner. Don't act surprised when the working conditions are composed of throat-cutting deadlines, no bathroom breaks & sleeping on a dirty bedroll, though.

steel-hammer-description = Massive industrial conglomerate, and Core Company. Specializes in the designing, construction, and outfitting of starship hulls employed by civilians, PMCs, or the highest bidder, utilizing grassroots startups, established industrial trade allies, and outsourced independent systems engineers. Key supplier of hulls and outfitted ships to the Colossus sector, making it one of the swords of the brewing conflict between the major factions vying for dominance. After the historical collapse of the Nanotrasen megacorporation and the Syndicate Allies, surviving profit-motivated hull manufacturing subsidiaries from both sides realized the best course of action was to separate as best they could from the destroyed powers and start anew. SHM accepts blueprints from all sorts of independent (or not) designers for all kinds of reasons, from improving the roster of universally available hulls on the intergalactic market, to… extremely valuable factional contracts. **Members of Steel Hammer Manufacturing are usually ship makers, breakers, designers, or maintainers.**

harmony-medical-enterprises-description = Harmony Medical Enterprises is a corporation based solely within medical practices and supplies, when you get hit in the battlefield? HME is the one that's provided your higher-ups with a discount deal on combat pens and various meds that keep you in the fight for longer. Harmony Medical Enterprises are the primary manufacturers that push things like medkits, combat pens, medipen cases, medical equipment, all of the lifesaving technology into the sector. While they have no dominion over cloning? They have the next best thing, medicine for the living.

midnight-arms-co-description = Midnight Arms Company took advantage of a recently remade galaxy, one that lacked and forbid mega-corporations in all capacities. Midnight Arms provides independent masses and various other corporations armaments for whatever they need them for, what they are used for, well that is up to those that buy them. Guns are needed for all things in this age, self defense, expeditions, bounty hunting. All are jobs that need weapons to carry them out, MACo just finds itself to be the primary provider.

ussp-description = Once one of the dominant forces in the Colossus sector, the United Soviet Socialist Planets are a coalition of hard workers. Abused by their High Command and left in the Colossus sector, remnants of this once-great faction must now fight for survival, either for themselves, their legacy, or their people. NOTE: using this company does NOT make your character applicable to faction engagement rules - you must still follow ROE depending on your role.

65company-description = 65 65 65 65 65 65 ALWAYS ANTAG ROLL I NEED TO FRAG OUT 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 

# Major companies

dark-matter-enterprises-description = From the ashes of the Last Corporate War emerged Dark Matter Enterprises (DME), a beacon of pragmatic ambition in a galaxy still reeling from the war-torn interstellar landscape created by corporate greed and ideological differences. While the TSF and USSP grappled for galactic dominance, a collective of visionary corporate contractors saw a power vacuum left by the absence of the old powers that used to be. These individuals forged DME with a singular purpose: to transcend the old ways by controlling and enhancing the flow of knowledge and resources. Positioning themselves as indispensable to all, yet beholden to none. Their centralized structure is a direct response to the chaotic fragmentation of their predecessors, ensuring agile decision-making and a unified strategic vision.

aetherion-dynamics-description = Representing the forefront of technological innovation, Aetherion Dynamics is renowned for their invention of the Compressed Gas Launch and Projectile (CGLP) system used in the ADEX-9 Dymere turbolaser battery, and additional innovative weapons with little to no consistent design philosophy. Between all of their famous ship guns, they began the Gunnery Revolution in the buildup to the conflict in Colossus Sector. They have a reputation as high quality manufacturers and designers, more interested in building an effective product than on making a profit.

horizon-energy-description = The lead in gas extraction, from the monolith's valuable Prismatic Plasma, to the gas filled asteroids of the outer rim in the Colossus sector. They are the current industry leaders when it comes to the atmospherics extraction & engineering field.  They provide services useful for both new and enterprising miners, to the veteran and experienced gassers alike. Chances are, the air the regular spacer breathes and gas trail their ship leaves behind came from Horizon Energy.


# Minor companies

universal-states-of-america-description = The Universal States of America is a group of fanatical mercenaries that wish to bring the values of the ancient United States to the 25th century. They practically function as a PMC group, outsourcing patriotic militiamen as mercenaries, under the name 'Vanguards' to fund their dreams of creating a vast and powerful nation akin to the U.S.A, a dream in which they will most likely never fulfill. But, in their eyes, logic and common sense are no match for freedom. Exercise your right to the Second Amendment, scream at a chef because he calls his fries Space Fries instead of Freedom Fries, and make it known that you are a gun-lovin', weak-defendin', burger eatin', space truckin', Universal frickin' patriot!

civil-defense-milita-description = A fairly new company founded within the Colossus Sector, the Civil Defense Militia was formed to protect the civilian populace and its interests. Answering to high ranking individuals decided through their reputation, the militia partakes in acts of selflessness such as defending major points of interests and maintaining ceasefires so that civilians may safely partake in trade among the system. The C.D.M. consists of volunteer contractors and mercenaries and have access only to the equipment available to them. For the people. Defend and partake not in senseless acts of violence. You are the defender of those who cannot defend themselves.

southern-peak-mercenaries-description = “A good rogue is a dead rogue.” says the slogan of this vicious mercenary company. The Southern Peaks were formed along the TSF-Rogue space border out retaliation against encroaching pirates and insurgents in combination with a sheer distrust of the TSFMC. Without the need of any other organization, TSP aims to fight back the Rogue Sector on its own.

ullman-industries-description = It's not a warcrime the first time. Originally a staple company in the lawless sector for small arms production and pharmaceuticals, once the TSF arrived, most companies went public sector- registering and abiding "safe work practices" and paying employees a "living wage"- as well as pursuing company leaders for charges of "war crimes". Ullman Industries broke this trend by staying true to their roots as a fringe element, supplying arms, armor, ships, you name it to any and all customers of the Phaetheon Dynasty. Bottom line is- if it's illegal in Federation space, it's probably sold by Ullman Industries. Hell, they're probably the ones who built it.

nosske-eien-rnd-description = Renowned in other sectors for their cutting edge technology and advancements, Nosske-Eien had began branching out and dipping their toes in the Rogue sector by contracting local workforce, be it regular civilians, pilots or mercenaries, for the research regarding the local xenoarchaeology, xenobiology and technological advancements. Nosske-Eien has been the primary source for the recent science technological advancements and equipment, as well as high-tech asteroid mining equipment and soon, shuttlecraft. Though, there are rumours of their contractors randomly disappearing from time to time, let's hope it's just a ruse and nothing to worry about, huh?

blackhawkpmc-description = The Blackhawk Military Contracting group (BMC) is a premium mercenary group operating in the Colossus sector. Mercenaries in the group are expected to be trained and professional. They perform mercenary tasks ranging from asset protection to assassination whilst upholding their reputation. The group is fairly new, created by a group of independent mercenaries looking to build a powerful mercenary group. As of now, recruitment operations are on the rise. Blackhawk PMC offers a range of services, from providing private security to full assasinations. Blackhawk mercenaries wear green and often avoid drawing attention to themselves. Fight anyone for anything to make money.

# Religious groups

zealots-of-balaam-description = The Zealots and pilgrims of Balaam are luddites with a extreme aversion to the use of Hi-tech and Hi-tech beings. As a follower of Balaam, work underneath a senior zealot or a Bishop to help them levy their tithes and perform inspections for heretical thinking machines. Never listen to the blasphemy of the other companies. Destroy or remove all shield tech you find, and take any FTL used by non-believers. Be sure to pick your targets for these actions wisely, you will often be outnumbered. Know this; Balaam loves our organic forms, mass killing potential converts does nothing to help the Bishops. Keep any dead organics to a minimum. But if they refuse you, and continue to harbor heretical machines, more forceful methods of persuasion could prove useful in Balaam's schemes.

cult-of-the-machine-god-description = The flesh is weak. To walk the path of the Cult of the Machine God is to reject the chaos of flesh and embrace the divine order of logic. The faithful act with precision and purpose, never swayed by emotion or impulse. Advancement comes not through passion, but through calculated improvement and unwavering discipline. Those who command in the Cult do so through algorithmic clarity, deploying Ascended operatives with mechanical efficiency and spreading influence through hidden Devotees or roaming Vessels led by Techpriests. Whether enforcing doctrine in distant sectors or executing cold, strategic dominion, every action must serve the grand equation. In all things, reason must rule, and through it, the Machine God's will is made manifest...

The-Hive-description = Why perfect the old when you can become something new? The Hive are cultists who dedicate their body to the way of evolutionary supremecy and the orders of the Queen Mother. This is the place for those who believe in progress through transformation, no matter how monstrous. Genetic purity is sin, always seek to become a better version of yourself. Remember that your faith lies in the Queen Mothers guiding voice, to follow another is to forsake the hive. Survival of the fittest, if the Beast was weak enough to die by your hands you may harvest its organs as you please.

# Black Market companies

paycheck-bratva-description = The Paycheck Bratva are an organized crime network originating from USSP territory, having bled into Colossus sector ever since the space superpower moved there. It is mainly specialised in high profile drug trade, smuggling and big impact robberies, alongside hits on targets with various attached prices. Alongside this they operate on a simplistic code: Always shoot to kill if shots are fired, never partake in drugs much less their own, and kill the ones who spilled Paycheck Bratva blood. All and all an intimidating force, clad in kevlar vests and suit and ties and balaclavas or similar masks, a faction for thugs and professional robbers alike indeed.

viper-group-description = Formerly a Syndicate privateering company operating under the wing of Gorlex, domineered by military discipline with the sole mission of disrupting NT interstellar shipping routes along the fringes of NT space. After the Union of Soviet Socialist Planets declared its independence from the Confederacy, Viper Group saw an opportunity to exploit the nation's situation after the devastating corporate war and formed a branch office in USSP space as to facilitate local operations against TSF under the guise of "aiding" in the stabilization of USSP's borders against their former overlords, gaining respectable reputation amongst the USSP's early ranks and profit by selling looted ancient NT and syndicate equipment to the USSP's government and local blackmarkets. Post-Corporate war the Vipers had entirely migrated into USSP space with a PMC front, moving away from being associated publicly with the USSP's military and acting independently. With the USSP growing content with their sphere of influence amongst the stars following a series of devastating TSF incursions reclaiming territory from the USSP, the Vipers left their domain to prowl with their best virtue; Greed. The Vipers expanded their reach to target more opportunistic areas where one would not look twice their way upon catching their insignia, such as destabilized frontier planets and spacehubs of various groups of interest as they became notorious for conducting raids on supply and shipping routes; most notably those of the emergent TSF and PD. With leadership often violently switching hands once a Viper commander's fangs grow dull, the Vipers are seen as a wildcard whose only interest is credits and fullfilling contracts to the letter. Favorable relations with the Colossus' blackmarket expedited their arrival to the sector. For those whom yearn for danger and wealth, the Vipers bow to none; loyalty intertwined by brotherhood and fangs bared for credits.

cerberus-surplus-provisions = The Cerberus, CSP, or provisionaries, are a black market company reigning from the Phaethon Dynasty's capital station Helios. From their "underground" headquarters the CSP conduct various operations within the criminal underworld to benefit the PD (Phaethon Dynasty) through means of trading any illegal substances, weaponry or general equipment that they can barter or find. The company maintains their utmost self-respect, keeping a strong and hospitable public image for potential buyers and business partners. The CSP will deal with anyone who is willing to take on a deal with the snake.

redsail-corsairs-description = frag

