name: Publish

on:
  workflow_dispatch:

concurrency:
  group: publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml

    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 10.0.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform linux-x64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Generate Watchdog Manifest
      run: |
        SERVER_SHA256=$(sha256sum release/SS14.Server_linux-x64.zip | cut -d ' ' -f 1)
        CLIENT_SHA256=$(sha256sum release/SS14.Client.zip | cut -d ' ' -f 1)
        BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        VERSION=${{ github.run_number }}
        TAG_NAME="build-$VERSION"

        cat > release/manifest.json <<EOF
        {
          "builds": {
            "$VERSION": {
              "time": "$BUILD_TIME",
              "client": {
                "url": "https://github.com/${{ github.repository }}/releases/download/$TAG_NAME/SS14.Client.zip",
                "sha256": "$CLIENT_SHA256"
              },
              "server": {
                "linux-x64": {
                  "url": "https://github.com/${{ github.repository }}/releases/download/$TAG_NAME/SS14.Server_linux-x64.zip",
                  "sha256": "$SERVER_SHA256"
                }
              }
            }
          }
        }
        EOF

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_number }}
        name: Build ${{ github.run_number }}
        files: |
          release/SS14.Server_linux-x64.zip
          release/SS14.Client.zip
          release/manifest.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Latest Tag
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: "Latest Manifest"
        force_update_tag: true
        files: |
          release/manifest.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish changelog (Discord)
      continue-on-error: true
      run: Tools/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}
